name: Build

on:
  pull_request:
    branches:
      - dev
      - 'stable/**'
  push:
    branches:
      - 'feature/**'
      - 'backport/**'
      - 'alpha/**'
      - 'beta/**'
      - 'stable/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build and test
        run: ./gradlew clean build